### ISSUE TITLE
load function ignores Dict key type

### ISSUE THREAD

**Issue by mrmerkone** [bshishov/ggbot#2]
load function ignores key type while loading Dict

``` python
from typing import Dict
import ctor

class Foo:

    def __init__(self, name: str):
        self.name = name

data = {"1": {"name": "foo"}}

assert ctor.load(Dict[int, Foo], data) == {1: Foo(name="foo")}
```

**Comment by bshishov** [comment]
fixed in `ctor==0.3.3`
[see 3ae29fe314611240ac18cee008e31fe76088747e](https://github.com/bshishov/ctor/commit/3ae29fe314611240ac18cee008e31fe76088747e)
